[[CURRENCIES]]
code="SMTK"
issuer="GDTAXNEMF6BYNZQTIOKMHO7GAHAMKWZIVL4HEB3UR4UA3QGOQSUZPIBP"
name="ScoutMe Token"
desc="Utility token for ScoutMe sports talent ecosystem"
image="https://scoutme-apk.netlify.app/logo.png"